GET http://localhost:3000/api/patients

###

GET http://localhost:3000/api/patients/1

###

POST http://localhost:3000/api/patients
Content-Type: application/json

{
  "name": "Juan Perez",
  "phone": "123456789",
  "cedula": "V12345678"
}

###

PUT http://localhost:3000/api/patients/1
Content-Type: application/json

{
  "name": "Juan Perez Actualizado",
  "phone": "987654321",
  "cedula": "V87654321"
}

###

DELETE http://localhost:3000/api/patients/1
