GET http://localhost:3000/api/doctors

###

GET http://localhost:3000/api/doctors/1

###

POST http://localhost:3000/api/doctors
Content-Type: application/json

{
  "email": "doctor@clinica.com",
  "passwordHash": "hash123",
  "role": "doctor"
}

###

PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
  "email": "doctoractualizado@clinica.com",
  "passwordHash": "hash456",
  "role": "doctor"
}

###

DELETE http://localhost:3000/api/users/1
