GET http://localhost:3000/api/medical-history

###

GET http://localhost:3000/api/medical-history/1

###

POST http://localhost:3000/api/medical-history
Content-Type: application/json

{
  "medical_inform": "Diagnóstico de ejemplo",
  "treatment": "Tratamiento de ejemplo",
  "recipe": "Receta de ejemplo",
  "patient_id": 1,
  "doctor_id": 1
}

###

PUT http://localhost:3000/api/medical-history/1
Content-Type: application/json

{
  "medical_inform": "Diagnóstico actualizado",
  "treatment": "Tratamiento actualizado",
  "recipe": "Receta actualizada",
  "patient_id": 1,
  "doctor_id": 1
}

###

DELETE http://localhost:3000/api/medical-history/1
